# Copyright 2025 Telefónica Soluciones de Informática y Comunicaciones de España, S.A.U.
# PROJECT: fiware-data-access
#
# This software and / or computer program has been developed by Telefónica Soluciones
# de Informática y Comunicaciones de España, S.A.U (hereinafter TSOL) and is protected
# as copyright by the applicable legislation on intellectual property.
#
# It belongs to TSOL, and / or its licensors, the exclusive rights of reproduction,
# distribution, public communication and transformation, and any economic right on it,
# all without prejudice of the moral rights of the authors mentioned above. It is expressly
# forbidden to decompile, disassemble, reverse engineer, sublicense or otherwise transmit
# by any means, translate or create derivative works of the software and / or computer
# programs, and perform with respect to all or part of such programs, any type of exploitation.
#
# Any use of all or part of the software and / or computer program will require the
# express written consent of TSOL. In all cases, it will be necessary to make
# an express reference to TSOL ownership in the software and / or computer
# program.
#
# Non-fulfillment of the provisions set forth herein and, in general, any violation of
# the peaceful possession and ownership of these rights will be prosecuted by the means
# provided in both Spanish and international law. TSOL reserves any civil or
# criminal actions it may exercise to protect its rights.

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"
    networks:
      - fda-net

  mc:
    image: minio/mc:latest
    container_name: minio-mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set local http://minio:9000 admin admin123 &&
      mc admin info local &&
      mc mb --ignore-existing local/my-bucket &&
      mc admin trace -v -a local &&
      tail -f /dev/null
      "
    logging:
      driver: "json-file"
      options:
        max-size: "250m"      
    networks:
      - fda-net

  mongo:
    image: mongo:8.0
    container_name: mongo
    ports:
      - "27017:27017"
    logging:
      driver: "json-file"
      options:
        max-size: "250m"
    networks:
      - fda-net

  postgis:
    container_name: postgis
    hostname: postgis
    # Default env variables will be used if not specify in .env
    image: ${FDA_POSTGIS_IMAGE:-postgis/postgis:15-3.3}
    volumes:
      - ${FDA_DBPATH_POSTGIS:-/data/postgis}:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    command: postgres --shared_buffers=256MB --max_connections=500
    environment:
      POSTGRES_USER: ${FDA_PG_USER:-postgres}
      POSTGRES_PASSWORD: ${FDA_PG_PASSWORD:-postgres}
      POSTGRES_DB: ${FDA_PG_DB:-postgres}      
    logging:
      driver: "json-file"
      options:
        max-size: "250m"
    networks:
      - fda-net

  fda:
    container_name: fda
    build:
      context: ../
      dockerfile: Dockerfile
    image: fda
    depends_on:
      - minio
      - mongo
      - postgis
    ports:
      - '8080:8080'
    environment:
      - FDA_NODE_ENV=production
      - FDA_LOG_LEVEL=DEBUG
      - FDA_PG_USER= ${FDA_PG_USER:-postgres}
      - FDA_PG_PASSWORD= ${FDA_PG_PASSWORD:-postgres}
      - FDA_PG_HOST=postgis
      - FDA_PG_PORT=5432
      - FDA_PG_DB=${FDA_PG_DB:-postgres}
      - FDA_OBJSTG_USER=${MINIO_ROOT_USER}
      - FDA_OBJSTG_PASSWORD=${MINIO_ROOT_PASSWORD}
      - FDA_OBJSTG_ENDPOINT=minio:9000
      - FDA_MONGO_URI=mongodb://mongo:27017
    command: ['npm', 'start']
    logging:
      driver: "json-file"
      options:
        max-size: "250m"
    networks:
      - fda-net
    
networks:
  fda-net:
    driver: bridge
